// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj5EVNs8JQslcLkYRzmTjB4WxHpxMNABc',
    appId: '1:758764754429:web:f4c44b6b1e07b1298d7594',
    messagingSenderId: '758764754429',
    projectId: 'ciclesmart-6362e',
    authDomain: 'ciclesmart-6362e.firebaseapp.com',
    storageBucket: 'ciclesmart-6362e.appspot.com',
    measurementId: 'G-Z92N1B3EQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxmC5Ze_r-rIvCMclPI3QDfUgubuuQBq4',
    appId: '1:758764754429:android:997e598e39fd75208d7594',
    messagingSenderId: '758764754429',
    projectId: 'ciclesmart-6362e',
    storageBucket: 'ciclesmart-6362e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDApOFYcRYATR-6LCkOdOcXHiW8pMcRnMg',
    appId: '1:758764754429:ios:e9716daaa819d8428d7594',
    messagingSenderId: '758764754429',
    projectId: 'ciclesmart-6362e',
    storageBucket: 'ciclesmart-6362e.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDApOFYcRYATR-6LCkOdOcXHiW8pMcRnMg',
    appId: '1:758764754429:ios:69fb9fa9e77df96d8d7594',
    messagingSenderId: '758764754429',
    projectId: 'ciclesmart-6362e',
    storageBucket: 'ciclesmart-6362e.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
